### ISSUE TITLE
投資信託のデータ取得

### ISSUE THREAD

**Issue by lucidfrontier45** [utahta/jsm#21]
http://stocks.finance.yahoo.co.jp/stocks/history/?code=
で得られるデータは上場株式は(日付,始値,高値,安値,終値,出来高,調整後終値)なのに対し、投資信託は(日付,基準価額,純資産)と異なるので現状の`get_historical_prices`では対応できない。`PriceData`クラスも株価のみなのでかなり大きな修正が必要そうですが、対応する予定はありますか？

**Comment by utahta** [comment]
今のところ投資信託は対応する予定ないですね・・・。
既存を変更するのは大変そうなので、やるとしたら別クラスになりそうです。

**Comment by lucidfrontier45** [comment]
投資信託も取得できるPull Requestを投げました。

**Comment by utahta** [comment]
ありがとうございます！mm
